<a href="https://colab.research.google.com/github/ChavesZay/PythonPandas-CursoAlura/blob/main/CreandoDataFramePorDiferentesFuentes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import requests
import pandas as pd

In [ ]:
json=open('datos/alquiler.json')
print(json.read())

[{"Tipo":"Habitación","Distrito":"San Borja","Cuartos":1,"Vacantes":0,"Suites":0,"Area":40,"Valor":1700.0,"Mantenimiento":500.0,"Impuesto":60.0},
{"Tipo":"Casa","Distrito":"Lurigancho","Cuartos":2,"Vacantes":0,"Suites":1,"Area":100,"Valor":7000.0,"Mantenimiento":null,"Impuesto":null},
{"Tipo":"Local comercial","Distrito":"Ate","Cuartos":0,"Vacantes":4,"Suites":0,"Area":150,"Valor":5200.0,"Mantenimiento":4020.0,"Impuesto":1111.0},
{"Tipo":"Departamento","Distrito":"Pachacámac","Cuartos":1,"Vacantes":0,"Suites":0,"Area":15,"Valor":800.0,"Mantenimiento":390.0,"Impuesto":20.0},
{"Tipo":"Departamento","Distrito":"Ate","Cuartos":1,"Vacantes":0,"Suites":0,"Area":48,"Valor":800.0,"Mantenimiento":230.0,"Impuesto":null},
{"Tipo":"Departamento","Distrito":"Barranco","Cuartos":3,"Vacantes":1,"Suites":0,"Area":70,"Valor":1200.0,"Mantenimiento":null,"Impuesto":null},
{"Tipo":"Departamento","Distrito":"Comas","Cuartos":2,"Vacantes":0,"Suites":0,"Area":50,"Valor":1300.0,"Mantenimiento":301.0,"Impuesto":17.0},
{"Tipo":"Casa en condominio","Distrito":"Ate","Cuartos":5,"Vacantes":4,"Suites":5,"Area":750,"Valor":22000.0,"Mantenimiento":null,"Impuesto":null},
{"Tipo":"Casa en condominio","Distrito":"El Agustino","Cuartos":2,"Vacantes":2,"Suites":0,"Area":65,"Valor":1000.0,"Mantenimiento":null,"Impuesto":null},
{"Tipo":"Local comercial","Distrito":"Pachacámac","Cuartos":0,"Vacantes":3,"Suites":0,"Area":695,"Valor":35000.0,"Mantenimiento":19193.0,"Impuesto":3030.0}]

In [ ]:
df_json=pd.read_json('datos/alquiler.json')
df_json

,Tipo,Distrito,Cuartos,Vacantes,Suites,Area,Valor,Mantenimiento,Impuesto
0,Habitación,San Borja,1,0,0,40,1700,500.0,60.0
1,Casa,Lurigancho,2,0,1,100,7000,NaN,NaN
2,Local comercial,Ate,0,4,0,150,5200,4020.0,1111.0
3,Departamento,Pachacámac,1,0,0,15,800,390.0,20.0
4,Departamento,Ate,1,0,0,48,800,230.0,NaN
5,Departamento,Barranco,3,1,0,70,1200,NaN,NaN
6,Departamento,Comas,2,0,0,50,1300,301.0,17.0
7,Casa en condominio,Ate,5,4,5,750,22000,NaN,NaN
8,Casa en condominio,El Agustino,2,2,0,65,1000,NaN,NaN
9,Local comercial,Pachacámac,0,3,0,695,35000,19193.0,3030.0

In [ ]:
txt=open('datos/alquiler.txt')
print(txt.read())

Tipo	Distrito	Cuartos	Vacantes	Suites	Area	Valor	Mantenimiento	Impuesto
Habitación	San Borja	1	0	0	40	1700	500	60
Casa	Lurigancho	2	0	1	100	7000
Local comercial	Ate	0	4	0	150	5200	4020	1111
Departamento	Pachacámac	1	0	0	15	800	390	20
Departamento	Ate	1	0	0	48	800	230
Departamento	Barranco	3	1	0	70	1200
Departamento	Comas	2	0	0	50	1300	301	17
Casa en condominio	Ate	5	4	5	750	22000
Casa en condominio	El Agustino	2	2	0	65	1000
Local comercial	Pachacámac	0	3	0	695	35000	19193	3030

In [ ]:
df_txt=pd.read_table('datos/alquiler.txt')
df_txt

,Tipo,Distrito,Cuartos,Vacantes,Suites,Area,Valor,Mantenimiento,Impuesto
0,Habitación,San Borja,1,0,0,40,1700,500.0,60.0
1,Casa,Lurigancho,2,0,1,100,7000,NaN,NaN
2,Local comercial,Ate,0,4,0,150,5200,4020.0,1111.0
3,Departamento,Pachacámac,1,0,0,15,800,390.0,20.0
4,Departamento,Ate,1,0,0,48,800,230.0,NaN
5,Departamento,Barranco,3,1,0,70,1200,NaN,NaN
6,Departamento,Comas,2,0,0,50,1300,301.0,17.0
7,Casa en condominio,Ate,5,4,5,750,22000,NaN,NaN
8,Casa en condominio,El Agustino,2,2,0,65,1000,NaN,NaN
9,Local comercial,Pachacámac,0,3,0,695,35000,19193.0,3030.0

In [ ]:
df_xlsx=pd.read_excel('datos/alquiler.xlsx')
df_xlsx

,Tipo,Distrito,Cuartos,Vacantes,Suites,Area,Valor,Mantenimiento,Impuesto
0,Habitación,San Borja,1,0,0,40,1700,500.0,60.0
1,Casa,Lurigancho,2,0,1,100,7000,NaN,NaN
2,Local comercial,Ate,0,4,0,150,5200,4020.0,1111.0
3,Departamento,Pachacámac,1,0,0,15,800,390.0,20.0
4,Departamento,Ate,1,0,0,48,800,230.0,NaN
5,Departamento,Barranco,3,1,0,70,1200,NaN,NaN
6,Departamento,Comas,2,0,0,50,1300,301.0,17.0
7,Casa en condominio,Ate,5,4,5,750,22000,NaN,NaN
8,Casa en condominio,El Agustino,2,2,0,65,1000,NaN,NaN
9,Local comercial,Pachacámac,0,3,0,695,35000,19193.0,3030.0

Cuando usamos la función read_html() en una URL o archivo HTML que contenga más de una tabla, cada una es convertida en un DataFrame y todas se almacenan en una lista de Python, es decir, la función read_html() devuelve una lista de DataFrames.

In [ ]:
df_html=pd.read_html('datos/datos_html_1.html')
df_html[0] # 0 porq lo transforma en lista

,Año,Campeón,Subcampeón,Sede
0,2018,Francia,Croacia,Rusia
1,2014,Alemania,Argentina,Brasil
2,2010,España,Holanda,Sudáfrica
3,2006,Italia,Francia,Alemania
4,2002,Brasil,Alemania,Corea S. y Japón
5,1998,Francia,Brasil,Francia
6,1994,Brasil,Italia,Estados Unidos
7,1990,Alemania,Argentina,Italia
8,1986,Argentina,Alemania (RFA),México
9,1982,Italia,Alemania (RFA),España
10,1978,Argentina,Holanda,Argentina
11,1974,Alemania (RFA),Holanda,Alemania (RFA)
12,1970,Brasil,Italia,México
13,1966,Inglaterra,Alemania (RFA),Inglaterra
14,1962,Brasil,Checoslovaquia,Chile
15,1958,Brasil,Suecia,Suecia
16,1954,Alemania (RFA),Hungría,Suiza
17,1950,Uruguay,Brasil,Brasil
18,1946,No celebrado (II Guerra Mundial),No celebrado (II Guerra Mundial),No celebrado (II Guerra Mundial)
19,1942,No celebrado (II Guerra Mundial),No celebrado (II Guerra Mundial),No celebrado (II Guerra Mundial)
20,1938,Italia,Hungría,Francia
21,1934,Italia,Checoslovaquia,Italia
22,1930,Uruguay,Argentina,Uruguay

In [ ]:
resp = requests.get('https://federalreserve.gov/releases/h3/current/default.htm')
df_html2 = pd.read_html(resp.text)  # Devolver una lista de DataFrames
len(df_html2) #El sitio tiene 3 tablas

3

In [ ]:
df_html2[0]

                  Date      Reserve balances required  \
                  Date Reserve balance requirements 1
0              Month 7                        Month 7
1            Aug. 2019                         134639
2           Sept. 2019                         134707
3            Oct. 2019                         134998
4            Nov. 2019                         140705
5            Dec. 2019                         138984
6            Jan. 2020                         144816
7            Feb. 2020                         138370
8            Mar. 2020                         113139
9            Apr. 2020                              0
10            May 2020                              0
11           June 2020                              0
12           July 2020                              0
13           Aug. 2020                              0
14                 NaN                            NaN
15  Two weeks ending 8             Two weeks ending 8
16       July 15, 2020                              0
17       July 29, 2020                              0
18       Aug. 12, 2020                              0
19       Aug. 26, 2020                              0
20       Sept. 9, 2020                              0

                                                               \
   Top of penalty- free band 2 Bottom of penalty- free band 3
0                      Month 7                        Month 7
1                       148114                         121167
2                       148188                         121227
3                       148509                         121489
4                       154787                         126625
5                       152893                         125076
6                       159309                         130326
7                       152218                         124524
8                       124461                         101817
9                            0                              0
10                           0                              0
11                           0                              0
12                           0                              0
13                           0                              0
14                         NaN                            NaN
15          Two weeks ending 8             Two weeks ending 8
16                           0                              0
17                           0                              0
18                           0                              0
19                           0                              0
20                           0                              0

   Reserve balances maintained 4  \
                           Total
0                        Month 7
1                        1520876
2                        1439771
3                        1481513
4                        1529341
5                        1630090
6                        1645384
7                        1656989
8                        2045148
9                        2953586
10                       3217635
11                       3043556
12                       2718529
13                       2799719
14                           NaN
15            Two weeks ending 8
16                       2795785
17                       2623526
18                       2751124
19                       2821740
20                       2854690

                                                                  \
   Balances maintained to satisfy reserve balance requirements 5
0                                             Month 7
1                                              147555
2                                              147498
3                                              148050
4                                              154256
5                                              152562
6                                              158765
7                                              151612
8                                              124147
9                                                   0
10                                                  0
11                                                  0
12                                                  0
13                                                  0
14                                                NaN
15                                 Two weeks ending 8
16                                                  0
17                                                  0
18                                                  0
19                                                  0
20                                                  0


   Balances maintained that exceed the top of the penalty- free band 6
0                                             Month 7
1                                             1373321
2                                             1292273
3                                             1333462
4                                             1375085
5                                             1477528
6                                             1486619
7                                             1505377
8                                             1921000
9                                             2953586
10                                            3217635
11                                            3043556
12                                            2718529
13                                            2799719
14                                                NaN
15                                 Two weeks ending 8
16                                            2795785
17                                            2623526
18                                            2751124
19                                            2821740
20                                            2854690

In [ ]:
df_html2[1]

                  Date            Reserves                      \
                  Date             Total 1            Required
0              Month 7             Month 7             Month 7
1            Aug. 2019             1586844              200608
2           Sept. 2019             1504805              199741
3            Oct. 2019             1547136              200621
4            Nov. 2019             1595222              206586
5            Dec. 2019             1698344              207239
6            Jan. 2020             1715219              214652
7            Feb. 2020             1726943              208324
8            Mar. 2020             2099369              167360
9            Apr. 2020             2953586                   0
10            May 2020             3217635                   0
11           June 2020             3043556                   0
12           July 2020             2718529                   0
13           Aug. 2020             2799719                   0
14                 NaN                 NaN                 NaN
15  Two weeks ending 8  Two weeks ending 8  Two weeks ending 8
16       July 15, 2020             2795785                   0
17       July 29, 2020             2623526                   0
18       Aug. 12, 2020             2751124                   0
19       Aug. 26, 2020             2821740                   0
20       Sept. 9, 2020             2854690                   0

          Vault cash 2                                      \
                 Total Used to satisfy required reserves 3
0              Month 7                             Month 7
1                78451                               65969
2                76550                               65035
3                76660                               65623
4                76921                               65881
5                80168                               68255
6                81216                               69835
7                80735                               69954
8                77114                               54222
9                88104                                   0
10              101345                                   0
11              104201                                   0
12               98392                                   0
13               95327                                   0
14                 NaN                                 NaN
15  Two weeks ending 8                  Two weeks ending 8
16               99459                                   0
17               97225                                   0
18               95638                                   0
19               95066                                   0
20               95313                                   0

                             Monetary base                              \
             Surplus 4             Total 5 Total balances maintained 6
0              Month 7             Month 7                     Month 7
1                12483             3271378                     1520876
2                11516             3202668                     1439771
3                11037             3252807                     1481513
4                11040             3315551                     1529341
5                11914             3426464                     1630090
6                11381             3442569                     1645384
7                10781             3454474                     1656989
8                22892             3883155                     2045148
9                88104             4844940                     2953586
10              101345             5149527                     3217635
11              104201             5001978                     3043556
12               98392             4700365                     2718529
13               95327             4807394                     2799719
14                 NaN                 NaN                         NaN
15  Two weeks ending 8  Two weeks ending 8          Two weeks ending 8
16               99459             4772522                     2795785
17               97225             4609143                     2623526
18               95638             4750981                     2751124
19               95066             4830999                     2821740
20               95313             4876690                     2854690


   Currency in circulation
0                  Month 7
1                  1750502
2                  1762898
3                  1771294
4                  1786209
5                  1796375
6                  1797185
7                  1797485
8                  1838007
9                  1891355
10                 1931891
11                 1958422
12                 1981836
13                 2007675
14                     NaN
15      Two weeks ending 8
16                 1976737
17                 1985617
18                 1999857
19                 2009260
20                 2022000

In [ ]:
df_html[2]

                  Date Borrowings from the Federal Reserve  \
                  Date                               Total
0              Month 3                             Month 3
1            Aug. 2019                                 117
2           Sept. 2019                                 101
3            Oct. 2019                                  63
4            Nov. 2019                                  26
5            Dec. 2019                                  21
6            Jan. 2020                                   6
7            Feb. 2020                                   3
8            Mar. 2020                               40554
9            Apr. 2020                              124461
10            May 2020                              111845
11           June 2020                               97671
12           July 2020                               92943
13           Aug. 2020                               83126
14                 NaN                                 NaN
15  Two weeks ending 4                  Two weeks ending 4
16       July 15, 2020                               94326
17       July 29, 2020                               92428
18       Aug. 12, 2020                               85636
19       Aug. 26, 2020                               82030
20       Sept. 9, 2020                               80170

                                                                \
               Primary           Secondary            Seasonal
0              Month 3             Month 3             Month 3
1                   16                   0                 101
2                   15                   0                  86
3                    4                   0                  59
4                    4                   0                  22
5                   10                   0                  11
6                    5                   0                   1
7                    3                   0                   0
8                19538                   0                   0
9                38299                   0                   0
10               22180                   0                   2
11                8456                   0                  11
12                4670                   0                  26
13                2851                   0                  38
14                 NaN                 NaN                 NaN
15  Two weeks ending 4  Two weeks ending 4  Two weeks ending 4
16                5055                   0                  21
17                4376                   0                  31
18                3111                   0                  37
19                2651                   0                  41
20                2786                   0                  34

                             Nonborrowed reserves 2
   Other credit extensions 1 Nonborrowed reserves 2
0                    Month 3                Month 3
1                          0                1586727
2                          0                1504704
3                          0                1547073
4                          0                1595196
5                          0                1698323
6                          0                1715213
7                          0                1726939
8                      21015                2058816
9                      86162                2829125
10                     89663                3105791
11                     89204                2945885
12                     88248                2625585
13                     80237                2716593
14                       NaN                    NaN
15        Two weeks ending 4     Two weeks ending 4
16                     89251                2701459
17                     88021                2531099
18                     82488                2665489
19                     79339                2739710
20                     77350                2774520